version: 2.1    
jobs:
  build: 
    parameters:
      run_test:
        description: "When to run tests"
        default: false
        type: boolean

    machine: true

    steps:
      - run: 
          name: build step
          command: echo "run build step"  
      - when:
          condition: << parameters.run_test >>
          steps:
            - run: echo " run my tests"  
#       - run:
#           name: Set checkout bit to true
#           command: |
#               curl -v -H 'Circle-Token: "'"$CIRCLECI_TOKEN"'"' --header "Content-Type: application/json" -d '{
#               "branch": "'"$CIRCLE_BRANCH"'",
#               "parameters": {
#                 "run_test": true
#               }}' "https://circleci.com/api/v2/project/github/HennaAbbas/Test_repo/pipeline"
              
      - run:
          name: Set checkout bit to true
          command: |
            curl --user ${CIRCLE_TOKEN}: \
            --data '{"branch":"test-api","parameters":{"run_test":true}}'
            --data build_parameters[CIRCLE_JOB]=deploy_docker \
            
            https://circleci.com/api/v1.1/project/github/HennaAbbas/Test_repo/pipeline
        
workflows:
  build-app:
    jobs:
      - build 
      - build:
          run_test: true
