version: 2.1

orbs:
  cloudwheel-lowell: greenbird/cloudwheel-common@1.0.14
  cloudwheel: greenbird/cloudwheel@1.0.25

workflows:
  release-build:
    jobs:
      - cloudwheel-lowell/maven-build-release:
          # context: cloudwheel-common
          executor: cloudwheel-lowell/linux
          filters:
            branches:
              only:
                - master
      - cloudwheel-lowell/maven-nexus-deploy:
          image: cloudwheel-lowell/linux
          # context: cloudwheel-common
          filters:
            branches:
              only:
                - master
          requires:
            - cloudwheel-lowell/maven-build-release
            
