version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-staging:
    executor:
      name: node/default
    steps:
      - checkout
      - run: echo 'export MY_ENV_VAR="FOO"' >> $BASH_ENV
      - run:
          name: Committing Build to Staging
          command: |
            echo "staging"

  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout


  build_regression_db_non_oracle:
    machine: true
    steps:
      - run:
#           <<: *env
          name: "Deploy Over SSH (Live)"
          command: |
            echo "hello worrld!"
  build_regression_db_non_oracle_java_11:
    machine: true
    steps:
      - run:
#           <<: *env
          name: "Deploy Over SSH (Live)"
          command: |
            echo "hello worrld!"            
  deploy-staging:
    machine: true
    steps:
      - run:
#           <<: *env
          name: "Deploy Over SSH (Staging)"
          command: |
            echo "hello worlds"
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"

workflows:
#   deploy-live:
#     jobs:
#       - deploy-live:
#           filters:
#             branches:
#               only:
#                 - master
#test

  deploy-staging:
    jobs:
      - install-and-test
      - deploy-staging:
          requires:
            - install-and-test
      - build-staging:
          requires:
            - install-and-test 
      - build_regression_db_non_oracle
      - build_regression_db_non_oracle_java_11
      
  deploy-live:
    jobs:
      - install-and-test
      - deploy-staging:
          requires:
            - install-and-test
      - build-staging:
          requires:
            - install-and-test 
      - build_regression_db_non_oracle
      - build_regression_db_non_oracle_java_11
      





