version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"

      - run: echo "hii"

      - run : echo "hiiii"
      - run : sleep 20 
 
      
workflows:
  version: 2
  default:
    jobs:
      - build
#test
