# aliases:
#   env: &env
#     environment:
#       SSH_PORT: 18765
#   workflows: &workflows
#     filters:
#       branches:
#         only:
#           - staging

version: 2.1

orbs:
  node: circleci/node@1.1.6

jobs:
  build-staging:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Committing Build to Staging
          command: |
            echo "staging"

  install-and-test:
    executor:
      name: node/default
    steps:
      - checkout


  deploy-live:
    machine: true
    steps:
      - run:
#           <<: *env
          name: "Deploy Over SSH (Live)"
          command: |
            echo "hello worrld!"
  deploy-staging:
    machine: true
    steps:
      - run:
#           <<: *env
          name: "Deploy Over SSH (Staging)"
          command: |
            echo "hello worlds"
  build:
    docker:
      - image: circleci/golang:1.9.6
    steps:
      - run: echo "hello world 1"

workflows:
#   deploy-live:
#     jobs:
#       - deploy-live:
#           filters:
#             branches:
#               only:
#                 - master

  deploy-staging:
    jobs:
      - install-and-test
      - deploy-staging:
          requires:
            - install-and-test
      - build-staging:
          requires:
            - install-and-test 
      - deploy-live:
          type: approval
      



# version: 2.1
# jobs:
#   build:
#     docker:
#       - image: circleci/golang:1.9.6
#     steps:
#       - run: echo "hello world 1"

#       - run: echo "hii"

#       - run : echo "hiiii"
#       - run : sleep 20 
 
      
# workflows:
#   version: 2
#   default:
#     jobs:
#       - build

