version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8.12-browsers
      
    steps:

      - run : echo "hello world! this is the build job" 
      - run: echo "${CIRCLE_BRANCH}"
      - run:
          name: "Setup custom environment variables"
          command: echo 'export MY_BRANCH="${CIRCLE_BRANCH}"' >> $BASH_ENV      
      - run: echo "${MY_BRANCH}"    
      - run: echo "https://bitbucket.org/ed-app/ed/branches/compare/${CIRCLE_SHA1}%0D${TEST_VAR}#commits"
      - run: echo "https://bitbucket.org/ed-app/ed/branches/compare/${CIRCLE_SHA1}${TEST_VAR}#commits"      
      - run:
          name: add environment variable
          command: |
#            curl -u "${MY_CIRCLE_TOKEN}": -X POST --header "Content-Type: application/json" -d '{"parameters": {"my_branch_name": "<< pipeline.git.branch >>", "my_param": "Hello"}}' https://circleci.com/api/v2/project/github/HennaAbbas/test_/pipeline 
            BUILD_INFO=$(curl -X POST -H "Circle-Token: ${MY_CIRCLE_TOKEN}" -H "Content-Type: application/json" -d "{ \"parameters\": { \"my_branch_name\": \"<< pipeline.git.branch >>\" } }" "https://circleci.com/api/v2/project/github/HennaAbbas/test_/pipeline")
    docker:
      - image: circleci/python:3.8.12-node-browsers
      
    steps:
      - run : echo "hello world - test job"      
      

    
            
# # #
workflows:
    build_and_push:
      jobs:
        - build   
        - test    
