version: 2.1    
jobs:
  build: 
    parameters:
      run_test:
        description: "When to run tests"
        default: false
        type: boolean

    machine: true

    steps:
      - run: 
          name: build step
          command: echo "run build step"  
      - when:
          condition: << parameters.run_test >>
          steps:
            - run: echo " run my tests"  
#       - run:
#           name: Set checkout bit to true
#           command: |
#               curl -v -H 'Circle-Token: "'"$CIRCLECI_TOKEN"'"' --header "Content-Type: application/json" -d '{
#               "branch": "'"$CIRCLE_BRANCH"'",
#               "parameters": {
#                 "run_test": true
#               }}' "https://circleci.com/api/v2/project/github/HennaAbbas/Test_repo/pipeline"
              
#       - run:
#           name: Set checkout bit to true
#           command: |
#             curl --username ${CIRCLE_TOKEN}: \
#             --data '{"branch":"test-api","parameters":{"run_test":true}}'\
            --url https://circleci.com/api/v2/project/github/HennaAbbas/Test_repo/pipeline
  command: |
            curl --location --request POST 'https://circleci.com/api/v2/project/github/HennaAbbas/Test_repo/pipeline' \
            --header 'Content-Type: application/json' \
            --data '{"branch":"test-api","parameters":{"run_test":true}}'\
            -u "cfa59a727c77098a62760cc3a1aeabb7d23ba410"            
         
        
workflows:
  build-app:
    jobs:
      - build 
      - build:
          run_test: true
